#include "Selector.h"

/*
FUNCION QUE INICIALIZA LA SECUENCIA PARA QUE EMPIECE AL PRINCIPIO DEL ARRAY DE HIJOS
*/
void Selector::onInitialize()
{
	m_Current = m_Children.begin(); // DEVUELVE UN ITERADOR APUNTANDO AL PRIMER ELEMENTO DEL VECTOR
}

/*
FUNCION QUE PROCESA CADA COMPORTAMIENTO HIJO ,UNO POR UNO, EN LA LISTA SALIENDO SI ALGUNO FALLA. 
DEVUELVE SUCCESS SI TODOS SE HAN EJECUTADO CORRECTAMENTE 
*/
Status Selector::update() 
{
	// SEGUIMOS HACIENDOLO HASTA QUE EL COMPORTAMIENTO HIJO DIGA QUE ESTA EJECUTANDOSE
	while(true)
	{
		Status s = (*m_Current)->tick();

		// SI EL HIJO TIENE EXITO O SIGUE EJECUTANDOSE, HACE LO MISMO 

		if(s != BH_FAILURE)
		{
			return s;
		}

		// SIGUE BUSCANDO UN COMPORTAMIENTO QUE TENGA EXITOHASTA QUE LLEGUE AL FINAL
		if(++m_Current == m_Children.end())
		{
			return BH_FAILURE;
		}
	}

	return BH_INVALID;  // INESPERADA SALIDA DEL BUCLE 
}
