#ifndef SELECTOR_H
#define SELECTOR_H

#include <iostream>
#include <vector>
#include <Composite.h>


using namespace std;

// EJECUTA CADA UNO DE SUS COMPORTAMIENTOS HIJOS ,EN ORDEN, HASTA QUE ENCUENTRA UN HIJO QUE O BIEN TIENE EXITO 
// O QUE DEVUELVE ESTADO DE RUNNING
class Selector: public Composite
{
	protected:

		virtual ~Selector();

		virtual void onInitialize() override;  // OVERRIDE INDICA QUE ESTAMOS INVAIDANDO OTRO FUNCION VIRTUAL
		virtual Status update() override;


		Behaviors::iterator m_Current; // PARA SABER EN QUE HIJO NOS ENCONTRAMOS ACTUALMENTE ( EL ITERATOR ES UN OBJETO QUE APUNTANDO A UN ELMENTO DE UN CONJUNTO DE ELEMENTOS 
											// (COMO UN ARRAY) TIENE LA HABILIDAD DE ITERAR A TRAVES DE LOS ELEMENTOS DE ESE RANGO QUE ESTA USANDO MEDIANTE DIFERENTES OPERADORES )
};

#endif // SEQUENCE_H