#include "Sequence.h"

/*
FUNCION QUE INICIALIZA LA SECUENCIA PARA QUE EMPIECE AL PRINCIPIO DEL ARRAY DE HIJOS
*/
void Sequence::onInitialize()
{
	m_CurrentChild = m_Children.begin(); // DEVUELVE UN ITERADOR APUNTANDO AL PRIMER ELEMENTO DEL VECTOR
}

/*
FUNCION QUE PROCESA CADA COMPORTAMIENTO HIJO ,UNO POR UNO, EN LA LISTA SALIENDO SI ALGUNO FALLA. 
DEVUELVE SUCCESS SI TODOS SE HAN EJECUTADO CORRECTAMENTE 
*/
Status Sequence::update() 
{
	// SEGUIMOS HACIENDOLO HASTA QUE EL COMPORTAMIENTO HIJO DIGA QUE ESTA EJECUTANDOSE

	while(true)
	{
		Status s = (*m_CurrentChild)->tick();

		// SI EL HIJO FALLA O SIGUE EJECUTANDOSE, HACE LO MISMO 

		if(s != BH_SUCCESS)
		{
			return s;
		}

		// AVANZAMOS HASTA QUE LLEGEMOS AL FINAL DEL ARRAY (++ operador de incremento de iterator)
		if(++m_CurrentChild == m_Children.end())
		{
			return BH_SUCCESS;
		}
	}

	return BH_INVALID;  // INESPERADA SALIDA DEL BUCLE 
}
